# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-12 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_stage', models.CharField(choices=[(1, '\u6e96\u5099\u968e\u6bb5'), (2, '\u69cb\u60f3\u8a2d\u8a08'), (3, '\u521d\u6b65\u8a2d\u8a08'), (4, '\u5408\u7d04\u8a2d\u8a08'), (5, '\u7d30\u90e8\u8a2d\u8a08')], max_length=32, verbose_name='\u8a2d\u8a08\u968e\u6bb5')),
                ('document_sn', models.CharField(max_length=18, verbose_name='\u6587\u4ef6\u7de8\u865f')),
                ('document_version', models.CharField(max_length=4, verbose_name='\u7248\u6b21')),
                ('document_name', models.CharField(max_length=80, verbose_name='\u61c9\u4ea4\u6587\u4ef6\u540d\u7a31')),
                ('document_purpose', models.CharField(max_length=80, verbose_name='\u5de5\u4f5c\u76ee\u7684')),
                ('document_content', models.TextField(verbose_name='\u5de5\u4f5c\u5167\u5bb9')),
                ('risk', models.TextField(verbose_name='\u98a8\u96aa\u8a55\u4f30\u53ca\u8a0e\u8ad6')),
                ('design_follows', models.TextField(verbose_name='\u8a2d\u8a08\u4f9d\u64da\uff0f\u6cd5\u898f')),
                ('document_ref', models.TextField(verbose_name='\u53c3\u8003\u6587\u4ef6')),
                ('author', models.CharField(max_length=64, verbose_name='\u627f\u8fa6\u4eba')),
            ],
        ),
    ]
